  # Default profile
  spring:
    profiles: default
    # Default user
    security:
      user:
        name: guest
        password: guest123
  bootrest:
    customproperty: hello
---
  spring:
    profiles: development
  server:
    port: 8080
---
  spring:
    profiles: production
  server:
    port: 9090
  